"use client"

import { useEffect, useState } from "react"
import { Auction, Bidder, Escalation, Message, Settlement } from "@/lib/auction-store"
import { AuctionShell } from "@/components/auction-shell"

type Props = { auctionId?: string }
const badgeClass = (value: string) => `status-badge ${value}`

export function OverviewView() {
  const [auctions, setAuctions] = useState<Auction[]>([]); const [wizard, setWizard] = useState(false)
  useEffect(() => { fetch("/api/auctions").then((r) => r.json()).then(setAuctions) }, [])
  return <AuctionShell title="Overview" eyebrow="Auction operations" action={<button className="primary-button" onClick={() => setWizard(true)}>+ New auction</button>}><div className="stats-grid"><Stat label="Live auctions" value={String(auctions.filter((a) => a.status === "live").length).padStart(2, "0")} note="Accepting bids" /><Stat label="Active bidders" value="11" note="Across 2 auctions" /><Stat label="Open escalations" value="02" note="1 high priority" /><Stat label="Pending settlement" value="01" note="Awaiting confirmation" /></div><div className="section-heading"><div><span className="eyebrow">Command board</span><h2>Your auctions</h2></div><a className="text-link" href="/auctions/live">View live auctions →</a></div><div className="market-grid">{auctions.map((auction) => <AuctionCard key={auction.id} auction={auction} />)}</div>{wizard && <NewAuctionWizard onClose={() => setWizard(false)} onCreated={(auction) => { setAuctions((items) => [auction, ...items]); setWizard(false) }} />}</AuctionShell>
}

export function LiveAuctionsView() { const [auctions, setAuctions] = useState<Auction[]>([]); useEffect(() => { fetch("/api/auctions").then((r) => r.json()).then((items: Auction[]) => setAuctions(items.filter((a) => a.status === "live"))) }, []); return <AuctionShell title="Live auctions" eyebrow="Active rooms"><div className="market-grid">{auctions.map((auction) => <AuctionCard key={auction.id} auction={auction} />)}</div></AuctionShell> }

export function AuctionDetailView({ auctionId = "AUC-1048" }: Props) {
  const [data, setData] = useState<{ auction: Auction; bidders: Bidder[] } | null>(null); const [selected, setSelected] = useState<Bidder | null>(null); const [events, setEvents] = useState<string[]>([])
  useEffect(() => { fetch(`/api/auctions/${auctionId}`).then((r) => r.json()).then(setData); const source = new EventSource(`/api/auctions/${auctionId}/stream`); source.onmessage = (event) => { const value = JSON.parse(event.data); if (value.type !== "heartbeat") setEvents((items) => [`${value.type} · just now`, ...items].slice(0, 8)) }; return () => source.close() }, [auctionId])
  if (!data) return <AuctionShell title="Loading mission control" eyebrow="Auction room"><div className="empty-state">Connecting to auction stream…</div></AuctionShell>
  return <AuctionShell title="Mission control" eyebrow={data.auction.id} action={<span className="live-indicator"><i /> Live stream connected</span>}><div className="detail-hero"><div><span className={badgeClass(data.auction.status)}>{data.auction.status}</span><h2>{data.auction.title}</h2><p>{data.auction.terms}</p></div><div className="hero-metrics"><Metric label="Top bid" value={data.auction.topBid} /><Metric label="Floor" value={data.auction.floor} /><Metric label="Ends" value="02:18:42" /></div></div><div className="mission-grid"><section className="panel"><PanelTitle label="Bidder roster" note={`${data.bidders.length} connected`} /><div className="roster-list">{data.bidders.map((bidder) => <button className="roster-row" key={bidder.id} onClick={() => setSelected(bidder)}><span className={`presence-dot ${bidder.status}`} /><span><strong>{bidder.name}</strong><small>{bidder.handle} · {bidder.connection}</small></span><b>{bidder.lastBid}</b></button>)}</div></section><section className="panel"><PanelTitle label="Activity feed" note="SSE / live" /><div className="activity-list">{events.length ? events.map((event, index) => <div className="activity-row" key={`${event}-${index}`}><span className="event-tag">LIVE</span><span>{event}</span></div>) : <div className="empty-state"><p>Waiting for live events</p><small>New bids and messages will appear here.</small></div>}</div></section><section className="panel"><PanelTitle label="Escalation queue" note="Needs review" /><div className="decision-card"><strong>Reserve exception request</strong><p>Rae Okafor asked for a reserve exception before placing a bid.</p><button className="secondary-button" onClick={() => setEvents((items) => ["escalation.resolved · just now", ...items])}>Resolve escalation</button></div><div className="decision-card"><strong>Operator controls</strong><p>Pause the room to stop new bids while you review a bidder thread.</p><button className="secondary-button">Pause auction</button></div></section></div>{selected && <BidderDrawer bidder={selected} onClose={() => setSelected(null)} />}</AuctionShell>
}

export function EscalationsView() { const [items, setItems] = useState<Escalation[]>([]); const [filter, setFilter] = useState("all"); useEffect(() => { fetch("/api/escalations").then((r) => r.json()).then(setItems) }, []); const update = async (item: Escalation) => { const status = item.status === "open" ? "resolved" : "open"; const response = await fetch(`/api/escalations/${item.id}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ status }) }); const updated = await response.json(); setItems((rows) => rows.map((row) => row.id === updated.id ? updated : row)) }; const visible = items.filter((item) => filter === "all" || item.status === filter || item.severity === filter); return <AuctionShell title="Escalations" eyebrow="Operator review"><div className="toolbar"><div className="segmented-control">{["all", "open", "resolved", "high"].map((value) => <button className={filter === value ? "active" : ""} key={value} onClick={() => setFilter(value)}>{value}</button>)}</div><span className="eyebrow">{visible.length} visible</span></div><div className="list-panel">{visible.map((item) => <div className="list-row" key={item.id}><div><span className={badgeClass(item.severity)}>{item.severity}</span><h3>{item.reason}</h3><p>{item.bidder} · {item.auctionId} · {item.status}</p></div><button className="secondary-button" onClick={() => update(item)}>{item.status === "open" ? "Resolve" : "Reopen"}</button></div>)}</div></AuctionShell> }
export function SettlementsView() {
  const [items, setItems] = useState<Settlement[]>([])
  const [selected, setSelected] = useState<Settlement | null>(null)
  const [busy, setBusy] = useState<string | null>(null)
  const create = async () => {
    const response = await fetch("/api/settlements", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ auctionId: "AUC-1048", winner: "Maya Chen", amount: "2.45", asset: "SOL", wallet: "7Gf...k91Q" }) })
    const created = await response.json()
    setItems((current) => [created, ...current])
    setSelected(created)
  }
  const runAction = async (item: Settlement, action: "verify" | "confirm" | "retry") => {
    setBusy(item.id)
    const response = await fetch(`/api/settlements/${item.id}`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ action }) })
    const updated = await response.json()
    setItems((current) => current.map((row) => row.id === updated.id ? updated : row))
    setSelected(updated)
    setBusy(null)
  }
  useEffect(() => { fetch("/api/settlements").then((r) => r.json()).then(setItems) }, [])
  return <AuctionShell title="Settlements" eyebrow="Simulated Solana ledger" action={<button className="primary-button" onClick={create}>Create payment request</button>}>
    <div className="settlement-summary"><div><span className="eyebrow">Settlement rail</span><strong>Solana Pay simulation</strong><small>Wallet signatures are simulated in this operator environment.</small></div><div className="settlement-summary-meta"><span>Network<strong>Devnet → Mainnet</strong></span><span>Verification<strong>Wallet + amount</strong></span></div></div>
    <div className="settlement-layout"><div className="list-panel">{items.map((item) => <button className={`settlement-row ${selected?.id === item.id ? "selected" : ""}`} key={item.id} onClick={() => setSelected(item)}><div className="settlement-row-main"><span className={badgeClass(item.status)}>{item.status}</span><h3>{item.amount} {item.asset} · {item.winner}</h3><p>{item.wallet} · {item.network}</p></div><div className="settlement-row-side"><strong>{item.verification.confirmations}</strong><small>confirmations</small></div></button>)}</div>{selected && <SettlementReceipt settlement={selected} busy={busy === selected.id} onAction={runAction} onClose={() => setSelected(null)} />}</div>
  </AuctionShell>
}

function SettlementReceipt({ settlement, busy, onAction, onClose }: { settlement: Settlement; busy: boolean; onAction: (settlement: Settlement, action: "verify" | "confirm" | "retry") => void; onClose: () => void }) {
  const canVerify = settlement.status === "pending"
  const canConfirm = settlement.status === "verifying"
  const canRetry = settlement.status === "failed"
  return <aside className="settlement-receipt"><div className="receipt-heading"><div><span className="eyebrow">Settlement receipt</span><h2>{settlement.amount} {settlement.asset}</h2><p>{settlement.winner} · {settlement.auctionId}</p></div><button className="icon-button" onClick={onClose}>×</button></div><div className="receipt-status"><span className={`status-pip ${settlement.status}`} /><div><strong>{settlement.status === "pending" ? "Payment request ready" : settlement.status === "verifying" ? "Verifying transaction" : settlement.status === "confirmed" ? "Settlement confirmed" : "Verification failed"}</strong><small>{settlement.updatedAt}</small></div></div><div className="receipt-grid"><div><span>Wallet</span><strong>{settlement.wallet}</strong></div><div><span>Network</span><strong>{settlement.network}</strong></div><div><span>Signature</span><strong>{settlement.signature}</strong></div><div><span>Request</span><strong>{settlement.paymentRequest}</strong></div></div><div className="verification-list"><div><span>Wallet match</span><b className={settlement.verification.wallet}>{settlement.verification.wallet}</b></div><div><span>Amount match</span><b className={settlement.verification.amount}>{settlement.verification.amount}</b></div><div><span>Confirmations</span><b>{settlement.verification.confirmations} / 32</b></div></div><div className="receipt-actions">{canVerify && <button className="primary-button" disabled={busy} onClick={() => onAction(settlement, "verify")}>{busy ? "Checking transaction…" : "Verify payment"}</button>}{canConfirm && <button className="primary-button" disabled={busy} onClick={() => onAction(settlement, "confirm")}>{busy ? "Finalizing…" : "Confirm settlement"}</button>}{canRetry && <button className="primary-button" disabled={busy} onClick={() => onAction(settlement, "retry")}>Create new request</button>}{settlement.status === "confirmed" && <button className="secondary-button" onClick={() => navigator.clipboard?.writeText(settlement.signature)}>Copy signature</button>}</div></aside>
}
export function SettingsView({ section = "rules" }: { section?: string }) { const rules = section === "rules"; const [settings, setSettings] = useState<Record<string, boolean>>({}); useEffect(() => { fetch("/api/settings").then((r) => r.json()).then(setSettings) }, []); const items = rules ? [{ key: "reserveProtection", title: "Reserve protection", body: "Block bids below the configured floor." }, { key: "autoExtend", title: "Auto-extend", body: "Extend the closing window when a bid arrives near close." }, { key: "humanApproval", title: "Human approval", body: "Route unusual bidder requests to the operator queue." }] : [{ key: "webChat", title: "Web chat", body: "Connected · 12 active sessions" }, { key: "email", title: "Email", body: "Connected · inbound replies enabled" }, { key: "sms", title: "SMS", body: "Not connected" }]; const flip = async (key: string) => { const next = { [key]: !settings[key] }; setSettings((current) => ({ ...current, ...next })); await fetch("/api/settings", { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify(next) }) }; return <AuctionShell title={rules ? "Rules & policies" : "Channel connections"} eyebrow="Configuration"><div className="settings-grid">{items.map((item) => <div className="setting-card" key={item.key}><button className="toggle-row" onClick={() => flip(item.key)}><span><strong>{item.title}</strong><small>{item.body}</small></span><span className={`toggle ${settings[item.key] ? "on" : ""}`}><span /></span></button><button className="text-button" onClick={() => flip(item.key)}>{settings[item.key] ? "Configure →" : "Connect →"}</button></div>)}</div></AuctionShell> }

function Stat({ label, value, note }: { label: string; value: string; note: string }) { return <div className="stat-card"><span>{label}</span><strong>{value}</strong><small>{note}</small></div> }
function Metric({ label, value }: { label: string; value: string }) { return <div><small>{label}</small><strong>{value}</strong></div> }
function PanelTitle({ label, note }: { label: string; note: string }) { return <div className="panel-title"><div><span className="eyebrow">{label}</span><h3>{note}</h3></div></div> }
function AuctionCard({ auction }: { auction: Auction }) { return <a className="market-card" href={`/auctions/${auction.id}`}><div className="auction-art"><span>AUCTION / {auction.id}</span><span>↗</span></div><div className="card-top"><span className={badgeClass(auction.status)}>{auction.status}</span><span>{auction.bidders} bidders</span></div><h3>{auction.title}</h3><div className="card-metrics"><span>Top bid <b>{auction.topBid}</b></span><span>Floor <b>{auction.floor}</b></span></div><div className="card-footer"><span>{auction.channels.join(" + ")}</span><span>Ends {new Date(auction.endsAt).toLocaleDateString()}</span></div></a> }
function NewAuctionWizard({ onClose, onCreated }: { onClose: () => void; onCreated: (auction: Auction) => void }) { const [step, setStep] = useState(1); const [form, setForm] = useState({ title: "", floor: "", terms: "", autoExtend: true, requiresApproval: true }); const update = (key: string, value: string | boolean) => setForm((current) => ({ ...current, [key]: value })); const create = async () => { const response = await fetch("/api/auctions", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ ...form, floor: `$${form.floor || "0"}`, status: "draft", endsAt: new Date(Date.now() + 7 * 86400000).toISOString(), channels: ["Web chat"] }) }); onCreated(await response.json()) }; return <div className="modal-backdrop"><div className="wizard modal-card"><div className="modal-heading"><div><span className="eyebrow">New auction · step {step} of 3</span><h2>{step === 1 ? "Describe the lot" : step === 2 ? "Set guardrails" : "Preview the live phrasing"}</h2></div><button className="icon-button" onClick={onClose}>×</button></div>{step === 1 && <div className="form-stack"><label>Lot title<input value={form.title} onChange={(e) => update("title", e.target.value)} placeholder="e.g. Signed first-edition design book" /></label><label>Opening floor<input value={form.floor} onChange={(e) => update("floor", e.target.value)} placeholder="1800" /></label><label>Terms<textarea value={form.terms} onChange={(e) => update("terms", e.target.value)} placeholder="Winner pays within 48 hours…" /></label></div>}{step === 2 && <div className="form-stack"><Toggle label="Auto-extend closing window" value={form.autoExtend} onChange={(value) => update("autoExtend", value)} /><Toggle label="Require operator approval for exceptions" value={form.requiresApproval} onChange={(value) => update("requiresApproval", value)} /><div className="policy-note">Bids below the floor will be rejected. New bidder requests are classified before acceptance.</div></div>}{step === 3 && <div className="preview-card"><span className="live-indicator"><i /> Live phrasing preview</span><p>“{form.title || "Your auction lot"} is open. Bids start at {form.floor ? `$${form.floor}` : "$0"}. {form.autoExtend ? "The closing window extends when a bid arrives near close." : "The auction closes at the scheduled time."}”</p><small>{form.requiresApproval ? "Operator approval is enabled for unusual requests." : "The agent can handle standard requests automatically."}</small></div>}<div className="modal-actions"><button className="secondary-button" onClick={step === 1 ? onClose : () => setStep(step - 1)}>{step === 1 ? "Cancel" : "Back"}</button>{step < 3 ? <button className="primary-button" disabled={step === 1 && !form.title} onClick={() => setStep(step + 1)}>Continue →</button> : <button className="primary-button" onClick={create}>Create auction</button>}</div></div></div> }
function Toggle({ label, value, onChange }: { label: string; value: boolean; onChange: (value: boolean) => void }) { return <button className="toggle-row" onClick={() => onChange(!value)}><span>{label}</span><span className={`toggle ${value ? "on" : ""}`}><span /></span></button> }
function BidderDrawer({ bidder, onClose }: { bidder: Bidder; onClose: () => void }) { const [messages, setMessages] = useState<Message[]>([]); const [reply, setReply] = useState(""); useEffect(() => { fetch(`/api/bidders/${bidder.id}`).then((r) => r.json()).then((data) => setMessages(data.messages)) }, [bidder.id]); const send = async () => { if (!reply.trim()) return; const response = await fetch(`/api/bidders/${bidder.id}`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ body: reply }) }); const created = await response.json(); setMessages((items) => [...items, created]); setReply("") }; return <div className="drawer-backdrop"><aside className="bidder-drawer"><div className="modal-heading"><div><span className="eyebrow">Bidder thread</span><h2>{bidder.name}</h2><p>{bidder.handle} · {bidder.connection}</p></div><button className="icon-button" onClick={onClose}>×</button></div><div className="thread">{messages.map((message) => <div className={`message ${message.author === "Operator" ? "operator" : ""}`} key={message.id}><div><strong>{message.author}</strong><span className="message-tag">{message.kind}</span></div><p>{message.body}</p><small>{message.at}</small></div>)}</div><div className="reply-box"><textarea value={reply} onChange={(e) => setReply(e.target.value)} placeholder="Write an operator reply…" /><button className="primary-button" onClick={send}>Send reply</button></div></aside></div> }
