import { EventEmitter } from "node:events"

export type AuctionStatus = "live" | "draft" | "closed" | "paused" | "settled"
export type MessageKind = "intent" | "question" | "bid" | "system" | "risk" | "condition" | "chatter" | "probe"
export type Channel = "telegram" | "whatsapp" | "email" | "web"
export type Policy = { revealFloor: boolean; revealLeader: boolean; revealBidCount: boolean; rounding: "none" | "5" | "10"; allowedConditions: { name: string; rule: string }[]; escalationSensitivity: "low" | "med" | "high" }
export type Auction = { id: string; title: string; description?: string; status: AuctionStatus; bidders: number; topBid: string; topBidCents?: number; floor: string; floorCents?: number; minIncrement?: string; endsAt: string; createdAt: string; terms: string; channels: string[]; autoExtend: boolean; requiresApproval: boolean; images?: string[]; allowedConditions?: string[]; policy?: Policy; inviteLinks?: Record<string, string>; inviteCode?: string }
export type Bidder = { id: string; auctionId?: string; name: string; handle: string; status: "active" | "quiet" | "dropped"; lastBid: string; connection: string; lastActiveAt?: string; paused?: boolean; flagged?: boolean; caspianConversationId?: string; caspianConnectionId?: string; caspianChannel?: string }
export type Message = { id: string; bidderId: string; author: string; body: string; kind: MessageKind; at: string; classification?: string; decision?: string; amount?: string; condition?: string }
export type Escalation = { id: string; auctionId: string; bidder: string; bidderId?: string; reason: string; severity: "high" | "medium" | "low"; status: "open" | "resolved"; createdAt: string; resolution?: string; suggestions?: string[] }
export type Settlement = { id: string; auctionId: string; winner: string; amount: string; asset: "SOL" | "USDC"; wallet: string; signature: string; status: "pending" | "verifying" | "confirmed" | "failed"; network: "Solana mainnet" | "Solana devnet"; paymentRequest: string; reference: string; verification: { wallet: "pending" | "matched" | "mismatch"; amount: "pending" | "matched" | "mismatch"; confirmations: number }; updatedAt: string }
export type AuditEvent = { id: string; auctionId: string; type: string; payload: unknown; at: string }

const now = () => new Date().toISOString()
const events = new EventEmitter()
const auctions: Auction[] = [
  { id: "AUC-1048", title: "Signed first-edition design book", status: "live", bidders: 7, topBid: "$2,450", floor: "$1,800", endsAt: "2026-08-09T18:30:00.000Z", createdAt: now(), terms: "Winner pays within 48 hours. Shipping included.", channels: ["Web chat", "Email"], autoExtend: true, requiresApproval: true },
  { id: "AUC-1047", title: "Studio portrait commission", status: "live", bidders: 4, topBid: "$980", floor: "$750", endsAt: "2026-08-10T13:00:00.000Z", createdAt: now(), terms: "Final deliverables due within 30 days.", channels: ["Web chat"], autoExtend: false, requiresApproval: false },
  { id: "AUC-1046", title: "Rare analog synthesizer", status: "draft", bidders: 0, topBid: "$0", floor: "$1,200", endsAt: "2026-08-14T20:00:00.000Z", createdAt: now(), terms: "Local pickup preferred.", channels: ["Web chat", "SMS"], autoExtend: true, requiresApproval: true },
]
const bidders: Record<string, Bidder[]> = { "AUC-1048": [{ id: "bd-1", auctionId: "AUC-1048", name: "Maya Chen", handle: "maya.chen", status: "active", lastBid: "$2,450", connection: "Web chat", lastActiveAt: now() }, { id: "bd-2", auctionId: "AUC-1048", name: "Jon Bell", handle: "jon.bell", status: "active", lastBid: "$2,300", connection: "Email", lastActiveAt: now() }, { id: "bd-3", auctionId: "AUC-1048", name: "Rae Okafor", handle: "rae.o", status: "quiet", lastBid: "$2,050", connection: "Web chat", lastActiveAt: now() }], "AUC-1047": [], "AUC-1046": [] }
const messages: Record<string, Message[]> = { "bd-1": [{ id: "m-1", bidderId: "bd-1", author: "Maya Chen", body: "I can move to $2,450 if shipping is included.", kind: "intent", at: "10:42:18" }, { id: "m-2", bidderId: "bd-1", author: "Auction agent", body: "Shipping is included for the winning bid. Would you like to place $2,450?", kind: "system", at: "10:42:36" }, { id: "m-3", bidderId: "bd-1", author: "Maya Chen", body: "Yes, place the bid.", kind: "bid", at: "10:42:51" }], "bd-2": [{ id: "m-5", bidderId: "bd-2", author: "Jon Bell", body: "Is there a certificate of authenticity?", kind: "question", at: "10:39:02" }], "bd-3": [{ id: "m-7", bidderId: "bd-3", author: "Rae Okafor", body: "This feels outside my budget now.", kind: "risk", at: "10:34:07" }] }
const escalations: Escalation[] = [{ id: "esc-1", auctionId: "AUC-1048", bidder: "Rae Okafor", reason: "Bidder requested a reserve exception", severity: "high", status: "open", createdAt: now(), bidderId: "bd-3", suggestions: ["Keep reserve unchanged", "Offer a future round"] }, { id: "esc-2", auctionId: "AUC-1047", bidder: "Jon Bell", reason: "Identity verification pending", severity: "medium", status: "open", createdAt: now() }]
const settlements: Settlement[] = [{ id: "set-1", auctionId: "AUC-1045", winner: "Liam Torres", amount: "3.2", asset: "SOL", wallet: "7Gf...k91Q", signature: "5oT...8xL", status: "confirmed", network: "Solana mainnet", paymentRequest: "solana:7Gf...k91Q?amount=3.2", reference: "auction-reference-1", verification: { wallet: "matched", amount: "matched", confirmations: 32 }, updatedAt: now() }]
const policies: Record<string, Policy> = {}
const audit: AuditEvent[] = []
const settings = { reserveProtection: true, autoExtend: true, humanApproval: false, webChat: true, email: true, sms: false, defaultEscalationSensitivity: "med" as const }
const channels: Record<string, { type: string; connected: boolean; lastMessageReceived?: string; authError?: string }> = {}

export const auctionStore = { auctions, bidders, messages, escalations, settlements, settings, policies, audit, channels, events }
export function emit(type: string, payload: unknown, auctionId?: string) { const event = { type, payload, at: now() }; events.emit("auction", event); if (auctionId) audit.unshift({ id: `evt-${Date.now()}-${Math.random().toString(36).slice(2, 6)}`, auctionId, type, payload, at: event.at }); return event }
export function createAuction(input: Omit<Auction, "id" | "createdAt" | "bidders" | "topBid">) { const auction: Auction = { ...input, id: `AUC-${1049 + auctions.length}`, createdAt: now(), bidders: 0, topBid: "$0", topBidCents: 0, inviteCode: String(1049 + auctions.length), inviteLinks: Object.fromEntries(input.channels.map((channel) => [channel, `${channel}://invite/${input.title.toLowerCase().replace(/[^a-z0-9]+/g, "-")}-${crypto.randomUUID().slice(0, 8)}`])) }; auctions.unshift(auction); bidders[auction.id] = []; emit("auction.created", auction, auction.id); return auction }
export function resolveEscalation(id: string, status: "resolved" | "open", resolution?: string) { const item = escalations.find((entry) => entry.id === id); if (item) { item.status = status; item.resolution = resolution; emit(`escalation.${status}`, item, item.auctionId) }; return item }
export function addMessage(bidderId: string, body: string, input: Partial<Message> = {}) { const message: Message = { id: `m-${Date.now()}`, bidderId, author: input.author || "Operator", body, kind: input.kind || "system", at: new Date().toLocaleTimeString([], { hour: "2-digit", minute: "2-digit", second: "2-digit" }), ...input }; messages[bidderId] = [...(messages[bidderId] || []), message]; const bidder = Object.values(bidders).flat().find((entry) => entry.id === bidderId); if (bidder) { bidder.lastActiveAt = now(); if (!bidder.paused) bidder.status = "active" }; emit("message.created", message, bidder?.auctionId); return message }
export function createSettlement(input: Pick<Settlement, "winner" | "amount" | "asset" | "wallet" | "auctionId">) { const reference = `ref-${crypto.randomUUID()}`; const settlement: Settlement = { ...input, id: `set-${Date.now()}`, signature: "awaiting-wallet-signature", status: "pending", network: "Solana devnet", reference, paymentRequest: `solana:${input.wallet}?amount=${encodeURIComponent(input.amount)}&reference=${reference}&label=Auction%20settlement`, verification: { wallet: "pending", amount: "pending", confirmations: 0 }, updatedAt: now() }; settlements.unshift(settlement); emit("settlement.created", settlement, input.auctionId); return settlement }
export function updateSettlement(id: string, status: Settlement["status"]) { const item = settlements.find((entry) => entry.id === id); if (item) { item.status = status; item.updatedAt = now(); if (status === "verifying") item.verification = { wallet: "matched", amount: "matched", confirmations: 1 }; if (status === "confirmed") { item.signature = `sim-${Date.now().toString(36)}`; item.network = "Solana mainnet"; item.verification = { wallet: "matched", amount: "matched", confirmations: 32 } }; if (status === "failed") item.verification = { wallet: "mismatch", amount: "pending", confirmations: 0 }; emit(`settlement.${status}`, item, item.auctionId) }; return item }
export function getSettlement(id: string) { return settlements.find((entry) => entry.id === id) }
export function findBidder(id: string) { return Object.values(bidders).flat().find((entry) => entry.id === id) }
export function findBidderByConversation(conversationId: string) { return Object.values(bidders).flat().find((entry) => entry.caspianConversationId === conversationId) }
export function findAuction(id: string) { return auctions.find((entry) => entry.id === id) }
export function findAuctionByCode(text: string) { const code = text.match(/\b(\d{4})\b/)?.[1]; return auctions.find((entry) => (entry.inviteCode === code || entry.id.endsWith(code || "")) && entry.status === "live") }
export function createBidder(auctionId: string, input: Partial<Omit<Bidder, "name" | "handle">> & Pick<Bidder, "name" | "handle">) { const existing = input.caspianConversationId ? findBidderByConversation(input.caspianConversationId) : undefined; if (existing) return existing; const { name, handle, ...rest } = input; const bidder: Bidder = { id: `bd-${Date.now()}`, auctionId, name, handle, status: "active", lastBid: "$0", connection: input.caspianChannel || "Email", lastActiveAt: now(), ...rest }; bidders[auctionId] = [...(bidders[auctionId] || []), bidder]; const auction = findAuction(auctionId); if (auction) auction.bidders = bidders[auctionId].length; emit("bidder.created", bidder, auctionId); return bidder }
export function createEscalation(input: Pick<Escalation, "auctionId" | "bidder" | "reason" | "severity"> & Partial<Pick<Escalation, "bidderId" | "suggestions">>) { const item: Escalation = { id: `esc-${Date.now()}`, status: "open", createdAt: now(), ...input }; escalations.unshift(item); emit("escalation.created", item, item.auctionId); return item }
export function reopenEscalation(id: string) { return resolveEscalation(id, "open") }
